#ifndef BIND_OF_POKE_CONFIG_H
#define BIND_OF_POKE_CONFIG_H

enum {
    LOGICAL_WIDTH = 960,
    LOGICAL_HEIGHT = 540,
    PLAYER_SIZE = 40,
    PROJECTILE_SIZE = 10,
    ENEMY_SIZE = 36,
    MAX_PROJECTILES = 96,
    MAX_ENEMIES = 16,
    MAX_WALLS = 8,
    ROOM_INSET = 28,
    MAX_FLOOR_ROOMS = 10,
    FLOOR_GRID_SIZE = 7,
    MAX_PICKUPS = 32,
    MAX_BOMBS = 8,
};

#define FIXED_TIMESTEP (1.0f / 60.0f)

#endif
